### ISSUE TITLE
add ledger support

### ISSUE THREAD

**Issue by colin-axner** [cosmos/interchain-accounts-demo#82]
- [ ] register messages on amino codec 
- [ ] add build support into Makefile (build using ibc-go Makefile works)
- [ ] add GetSignBytes

```
icad tx intertx register --from $DEMOWALLET_1 --connection-id connection-0 --chain-id test-1 --gas 150000  --ledger --node tcp://localhost:16657 --keyring-backend test -y
Default sign-mode 'direct' not supported by Ledger, using sign-mode 'amino-json'.
panic: expected *legacytx.LegacyMsg when using amino JSON

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/auth/legacy/legacytx.StdSignBytes({0x7fffe6951764, 0x6}, 0xa, 0x0, 0x0, {{0x0, 0x1f, 0x1f}, 0xc0016121e0}, {0xc00124c160, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.44.5/x/auth/legacy/legacytx/stdsign.go:58 +0x3ae
github.com/cosmos/cosmos-sdk/x/auth/tx.signModeLegacyAminoJSONHandler.GetSignBytes({}, 0x16122a8, {{0x7fffe6951764, 0xc0016122e8}, 0x4137d4, 0x2}, {0x1ef18a8, 0xc00141cd00})
	github.com/cosmos/cosmos-sdk@v0.44.5/x/auth/tx/legacy_amino_json.go:49 +0x1a7
github.com/cosmos/cosmos-sdk/x/auth/signing.SignModeHandlerMap.GetSignBytes({0x1, {0xc000259000, 0x2, 0x2}, 0xc00028b800}, 0x1f02d40, {{0x7fffe6951764, 0x6}, 0xa, 0x0}, ...)
	github.com/cosmos/cosmos-sdk@v0.44.5/x/auth/signing/handler_map.go:59 +0xa2
github.com/cosmos/cosmos-sdk/client/tx.Sign({{0x1f52b70, 0xc00141c6c0}, {0x1f3c178, 0xc00020eb40}, {0x1f22d98, 0x2db2e88}, 0xa, 0x0, 0x249f0, 0x0, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.44.5/client/tx/tx.go:441 +0x388
github.com/cosmos/cosmos-sdk/client/tx.BroadcastTx({{0xc0013719e0, 0x14, 0x18}, {0x1f5c478, 0xc001422180}, {0x7fffe6951764, 0x6}, {0x1f2aec8, 0xc00100ac40}, {0x1f50d38, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.44.5/client/tx/tx.go:132 +0x66d
github.com/cosmos/cosmos-sdk/client/tx.GenerateOrBroadcastTxWithFactory({{0xc0013719e0, 0x14, 0x18}, {0x1f5c478, 0xc001422180}, {0x7fffe6951764, 0x6}, {0x1f2aec8, 0xc00100ac40}, {0x1f50d38, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.44.5/client/tx/tx.go:51 +0x11f
github.com/cosmos/cosmos-sdk/client/tx.GenerateOrBroadcastTxCLI({{0xc0013719e0, 0x14, 0x18}, {0x1f5c478, 0xc001422180}, {0x7fffe6951764, 0x6}, {0x1f2aec8, 0xc00100ac40}, {0x1f50d38, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.44.5/client/tx/tx.go:31 +0x113
github.com/cosmos/interchain-accounts/x/inter-tx/client/cli.getRegisterAccountCmd.func1(0xc00122c780, {0xc0001509a0, 0x0, 0xe})
	github.com/cosmos/interchain-accounts/x/inter-tx/client/cli/tx.go:53 +0x2ab
github.com/spf13/cobra.(*Command).execute(0xc00122c780, {0xc0001508c0, 0xe, 0xe})
	github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc00026c500)
	github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.3.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.3.0/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0, {0xc000137ea8, 0x13})
	github.com/cosmos/cosmos-sdk@v0.44.5/server/cmd/execute.go:36 +0x1eb
main.main()
	github.com/cosmos/interchain-accounts/cmd/icad/main.go:13 +0x2c
```

**Comment by crodriguezvega** [comment]
Closing since we decided to archive the repo.
